export { default as BasicModal } from '@/common/modals/BasicModal.vue'
export { default as LoaderModal } from '@/common/modals/LoaderModal.vue'
export { default as ErrorModal } from '@/common/modals/ErrorModal.vue'
export { default as SuccessModal } from '@/common/modals/SuccessModal.vue'
export { default as CertificatesModal } from '@/common/modals/CertificatesModal.vue'
